export interface TemplateConfig {
  id: string
  name: string
  description: string
  layout: 'standard' | 'banner' | 'lateral'
  docBg: string
  text: string
  textMuted: string
  textFooter: string
  clientBlockBg: string
  clientBlockBorder: string
  clientEmptyBg: string
  clientEmptyBorder: string
  rowEven: string
  rowOdd: string
  rowHover: string
  borderLight: string
  totalBg: string
  totalBorder: string
  footerBorder: string
  inputBg: string
  inputPlaceholder: string
  editBorderDashed: string
  signatureBorder: string
  paymentBadgeBg: string
  paymentBadgeBorder: string
  paymentBadgeText: string
  borderRadius: string
  font?: string
}

const classique: TemplateConfig = {
  id: 'classique',
  name: 'Classique',
  description: 'Bordures pointillées, accent bleu-gris, style comptable',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#476388',
  textMuted: '#88A0BF',
  textFooter: '#88A0BF',
  clientBlockBg: '#ffffff',
  clientBlockBorder: '#bfcee1',
  clientEmptyBg: '#E5ECF4',
  clientEmptyBorder: '#88A0BF',
  rowEven: '#ffffff',
  rowOdd: '#fafbfd',
  rowHover: '06',
  borderLight: '#bfcee1',
  totalBg: '10',
  totalBorder: '25',
  footerBorder: '#bfcee1',
  inputBg: '#ffffff',
  inputPlaceholder: '#88A0BF',
  editBorderDashed: '#bfcee1',
  signatureBorder: '#bfcee1',
  paymentBadgeBg: '#f0f3f8',
  paymentBadgeBorder: '#bfcee1',
  paymentBadgeText: '#476388',
  borderRadius: '8px',
  font: 'Nunito',
}

const moderne: TemplateConfig = {
  id: 'moderne',
  name: 'Moderne',
  description: 'Bandeau coloré, neutres nets et contrastés',
  layout: 'banner',
  docBg: '#ffffff',
  text: '#09090b',
  textMuted: '#52525b',
  textFooter: '#a1a1aa',
  clientBlockBg: '#fafafa',
  clientBlockBorder: '#e4e4e7',
  clientEmptyBg: '#fafafa',
  clientEmptyBorder: '#d4d4d8',
  rowEven: '#ffffff',
  rowOdd: '#fafafa',
  rowHover: '06',
  borderLight: '#e4e4e7',
  totalBg: '10',
  totalBorder: '24',
  footerBorder: '#e4e4e7',
  inputBg: '#ffffff',
  inputPlaceholder: '#a1a1aa',
  editBorderDashed: '#d4d4d8',
  signatureBorder: '#d4d4d8',
  paymentBadgeBg: '#fafafa',
  paymentBadgeBorder: '#e4e4e7',
  paymentBadgeText: '#52525b',
  borderRadius: '10px',
}

const studio: TemplateConfig = {
  id: 'studio',
  name: 'Studio',
  description: 'Typographie affirmée, noir encre, hairlines',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#0a0a0a',
  textMuted: '#6f6f76',
  textFooter: '#a3a3ab',
  clientBlockBg: 'transparent',
  clientBlockBorder: '#ececef',
  clientEmptyBg: '#fafafa',
  clientEmptyBorder: '#d8d8dc',
  rowEven: '#ffffff',
  rowOdd: '#ffffff',
  rowHover: '04',
  borderLight: '#ececef',
  totalBg: '07',
  totalBorder: '22',
  footerBorder: '#ececef',
  inputBg: '#ffffff',
  inputPlaceholder: '#a3a3ab',
  editBorderDashed: '#d8d8dc',
  signatureBorder: '#d8d8dc',
  paymentBadgeBg: 'transparent',
  paymentBadgeBorder: '#ececef',
  paymentBadgeText: '#6f6f76',
  borderRadius: '2px',
  font: 'Sora',
}

const elegance: TemplateConfig = {
  id: 'elegance',
  name: 'Élégance',
  description: 'Serif raffiné, tons pierre, lignes fines',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#1c1917',
  textMuted: '#78716c',
  textFooter: '#a8a29e',
  clientBlockBg: 'transparent',
  clientBlockBorder: '#e7e5e4',
  clientEmptyBg: 'transparent',
  clientEmptyBorder: '#d6d3d1',
  rowEven: '#ffffff',
  rowOdd: '#ffffff',
  rowHover: '03',
  borderLight: '#e7e5e4',
  totalBg: '05',
  totalBorder: '16',
  footerBorder: '#d6d3d1',
  inputBg: '#ffffff',
  inputPlaceholder: '#a8a29e',
  editBorderDashed: '#d6d3d1',
  signatureBorder: '#d6d3d1',
  paymentBadgeBg: 'transparent',
  paymentBadgeBorder: '#e7e5e4',
  paymentBadgeText: '#78716c',
  borderRadius: '2px',
  font: 'EB Garamond',
}

const editorial: TemplateConfig = {
  id: 'editorial',
  name: 'Éditorial',
  description: 'Style revue, serif littéraire, papier chaud',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#292524',
  textMuted: '#78716c',
  textFooter: '#a8a29e',
  clientBlockBg: 'transparent',
  clientBlockBorder: '#e7e5e4',
  clientEmptyBg: 'transparent',
  clientEmptyBorder: '#d6d3d1',
  rowEven: '#ffffff',
  rowOdd: '#faf9f7',
  rowHover: '03',
  borderLight: '#e7e5e4',
  totalBg: '06',
  totalBorder: '18',
  footerBorder: '#d6d3d1',
  inputBg: '#ffffff',
  inputPlaceholder: '#a8a29e',
  editBorderDashed: '#d6d3d1',
  signatureBorder: '#d6d3d1',
  paymentBadgeBg: 'transparent',
  paymentBadgeBorder: '#e7e5e4',
  paymentBadgeText: '#78716c',
  borderRadius: '0px',
  font: 'Lora',
}

const audacieux: TemplateConfig = {
  id: 'audacieux',
  name: 'Audacieux',
  description: 'En-tête plein, formes généreuses, grotesque',
  layout: 'banner',
  docBg: '#ffffff',
  text: '#0f172a',
  textMuted: '#475569',
  textFooter: '#94a3b8',
  clientBlockBg: '#f1f5f9',
  clientBlockBorder: '#e2e8f0',
  clientEmptyBg: '#f8fafc',
  clientEmptyBorder: '#cbd5e1',
  rowEven: '#ffffff',
  rowOdd: '#f8fafc',
  rowHover: '06',
  borderLight: '#e2e8f0',
  totalBg: '14',
  totalBorder: '32',
  footerBorder: '#e2e8f0',
  inputBg: '#ffffff',
  inputPlaceholder: '#94a3b8',
  editBorderDashed: '#cbd5e1',
  signatureBorder: '#cbd5e1',
  paymentBadgeBg: '#f1f5f9',
  paymentBadgeBorder: '#e2e8f0',
  paymentBadgeText: '#475569',
  borderRadius: '16px',
  font: 'Archivo',
}

const carbone: TemplateConfig = {
  id: 'carbone',
  name: 'Carbone',
  description: 'Bandeau contrasté, gris profonds, géométrique',
  layout: 'banner',
  docBg: '#ffffff',
  text: '#18181b',
  textMuted: '#52525b',
  textFooter: '#a1a1aa',
  clientBlockBg: '#f4f4f5',
  clientBlockBorder: '#e4e4e7',
  clientEmptyBg: '#fafafa',
  clientEmptyBorder: '#d4d4d8',
  rowEven: '#ffffff',
  rowOdd: '#fafafa',
  rowHover: '06',
  borderLight: '#e4e4e7',
  totalBg: '12',
  totalBorder: '28',
  footerBorder: '#e4e4e7',
  inputBg: '#ffffff',
  inputPlaceholder: '#a1a1aa',
  editBorderDashed: '#d4d4d8',
  signatureBorder: '#d4d4d8',
  paymentBadgeBg: '#f4f4f5',
  paymentBadgeBorder: '#e4e4e7',
  paymentBadgeText: '#52525b',
  borderRadius: '6px',
  font: 'Space Grotesk',
}

const duo: TemplateConfig = {
  id: 'duo',
  name: 'Duo',
  description: 'En-tête bicolore accent + sombre',
  layout: 'banner',
  docBg: '#ffffff',
  text: '#0f172a',
  textMuted: '#64748b',
  textFooter: '#94a3b8',
  clientBlockBg: '#f1f5f9',
  clientBlockBorder: '#e2e8f0',
  clientEmptyBg: '#f8fafc',
  clientEmptyBorder: '#cbd5e1',
  rowEven: '#ffffff',
  rowOdd: '#f8fafc',
  rowHover: '06',
  borderLight: '#e2e8f0',
  totalBg: '10',
  totalBorder: '25',
  footerBorder: '#e2e8f0',
  inputBg: '#ffffff',
  inputPlaceholder: '#94a3b8',
  editBorderDashed: '#cbd5e1',
  signatureBorder: '#cbd5e1',
  paymentBadgeBg: '#f1f5f9',
  paymentBadgeBorder: '#e2e8f0',
  paymentBadgeText: '#64748b',
  borderRadius: '10px',
}

const horizon: TemplateConfig = {
  id: 'horizon',
  name: 'Horizon',
  description: 'Bandeau épuré, géométrie douce et aérée',
  layout: 'banner',
  docBg: '#ffffff',
  text: '#0f172a',
  textMuted: '#64748b',
  textFooter: '#94a3b8',
  clientBlockBg: '#f8fafc',
  clientBlockBorder: '#e2e8f0',
  clientEmptyBg: '#f8fafc',
  clientEmptyBorder: '#cbd5e1',
  rowEven: '#ffffff',
  rowOdd: '#f8fafc',
  rowHover: '05',
  borderLight: '#e2e8f0',
  totalBg: '10',
  totalBorder: '24',
  footerBorder: '#e2e8f0',
  inputBg: '#ffffff',
  inputPlaceholder: '#94a3b8',
  editBorderDashed: '#cbd5e1',
  signatureBorder: '#cbd5e1',
  paymentBadgeBg: '#f8fafc',
  paymentBadgeBorder: '#e2e8f0',
  paymentBadgeText: '#64748b',
  borderRadius: '12px',
  font: 'DM Sans',
}

const lateral: TemplateConfig = {
  id: 'lateral',
  name: 'Latéral',
  description: 'Barre latérale colorée avec infos société',
  layout: 'lateral',
  docBg: '#ffffff',
  text: '#0f172a',
  textMuted: '#64748b',
  textFooter: '#94a3b8',
  clientBlockBg: '#f8fafc',
  clientBlockBorder: '#e2e8f0',
  clientEmptyBg: '#f8fafc',
  clientEmptyBorder: '#cbd5e1',
  rowEven: '#ffffff',
  rowOdd: '#f8fafc',
  rowHover: '06',
  borderLight: '#e2e8f0',
  totalBg: '10',
  totalBorder: '25',
  footerBorder: '#e2e8f0',
  inputBg: '#ffffff',
  inputPlaceholder: '#94a3b8',
  editBorderDashed: '#cbd5e1',
  signatureBorder: '#cbd5e1',
  paymentBadgeBg: '#f8fafc',
  paymentBadgeBorder: '#e2e8f0',
  paymentBadgeText: '#64748b',
  borderRadius: '8px',
}

const prisme: TemplateConfig = {
  id: 'prisme',
  name: 'Prisme',
  description: 'Barre latérale, intérieur arrondi et lumineux',
  layout: 'lateral',
  docBg: '#ffffff',
  text: '#1e1b2e',
  textMuted: '#6e6a85',
  textFooter: '#a4a1b8',
  clientBlockBg: '#faf9fc',
  clientBlockBorder: '#eceaf2',
  clientEmptyBg: '#faf9fc',
  clientEmptyBorder: '#d9d6e4',
  rowEven: '#ffffff',
  rowOdd: '#fbfafd',
  rowHover: '06',
  borderLight: '#eceaf2',
  totalBg: '12',
  totalBorder: '26',
  footerBorder: '#eceaf2',
  inputBg: '#ffffff',
  inputPlaceholder: '#a4a1b8',
  editBorderDashed: '#d9d6e4',
  signatureBorder: '#d9d6e4',
  paymentBadgeBg: '#faf9fc',
  paymentBadgeBorder: '#eceaf2',
  paymentBadgeText: '#6e6a85',
  borderRadius: '10px',
  font: 'Outfit',
}

const pastel: TemplateConfig = {
  id: 'pastel',
  name: 'Pastel',
  description: 'Doux et arrondi, ambiance légère',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#3f3f46',
  textMuted: '#8b8b94',
  textFooter: '#b5b5bd',
  clientBlockBg: '#faf9fb',
  clientBlockBorder: '#eeedf2',
  clientEmptyBg: '#faf9fb',
  clientEmptyBorder: '#dcdae3',
  rowEven: '#ffffff',
  rowOdd: '#fcfbfd',
  rowHover: '06',
  borderLight: '#eeedf2',
  totalBg: '12',
  totalBorder: '26',
  footerBorder: '#eeedf2',
  inputBg: '#ffffff',
  inputPlaceholder: '#b5b5bd',
  editBorderDashed: '#dcdae3',
  signatureBorder: '#dcdae3',
  paymentBadgeBg: '#faf9fb',
  paymentBadgeBorder: '#eeedf2',
  paymentBadgeText: '#8b8b94',
  borderRadius: '14px',
  font: 'Quicksand',
}

const minimaliste: TemplateConfig = {
  id: 'minimaliste',
  name: 'Minimaliste',
  description: 'Ultra-épuré, traits fins, espace généreux',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#18181b',
  textMuted: '#71717a',
  textFooter: '#a1a1aa',
  clientBlockBg: 'transparent',
  clientBlockBorder: '#e4e4e7',
  clientEmptyBg: 'transparent',
  clientEmptyBorder: '#d4d4d8',
  rowEven: '#ffffff',
  rowOdd: '#ffffff',
  rowHover: '03',
  borderLight: '#e4e4e7',
  totalBg: '04',
  totalBorder: '12',
  footerBorder: '#e4e4e7',
  inputBg: '#ffffff',
  inputPlaceholder: '#a1a1aa',
  editBorderDashed: '#d4d4d8',
  signatureBorder: '#d4d4d8',
  paymentBadgeBg: 'transparent',
  paymentBadgeBorder: '#e4e4e7',
  paymentBadgeText: '#71717a',
  borderRadius: '0px',
}

const mono: TemplateConfig = {
  id: 'mono',
  name: 'Mono',
  description: 'Esprit technique, chasse fixe, grille stricte',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#18181b',
  textMuted: '#52525b',
  textFooter: '#a1a1aa',
  clientBlockBg: '#fafafa',
  clientBlockBorder: '#e4e4e7',
  clientEmptyBg: '#fafafa',
  clientEmptyBorder: '#d4d4d8',
  rowEven: '#ffffff',
  rowOdd: '#fafafa',
  rowHover: '05',
  borderLight: '#e4e4e7',
  totalBg: '08',
  totalBorder: '22',
  footerBorder: '#e4e4e7',
  inputBg: '#ffffff',
  inputPlaceholder: '#a1a1aa',
  editBorderDashed: '#d4d4d8',
  signatureBorder: '#d4d4d8',
  paymentBadgeBg: '#fafafa',
  paymentBadgeBorder: '#e4e4e7',
  paymentBadgeText: '#52525b',
  borderRadius: '0px',
  font: 'JetBrains Mono',
}

const compact: TemplateConfig = {
  id: 'compact',
  name: 'Compact',
  description: 'Dense et sans arrondis, efficace',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#09090b',
  textMuted: '#52525b',
  textFooter: '#a1a1aa',
  clientBlockBg: '#fafafa',
  clientBlockBorder: '#e4e4e7',
  clientEmptyBg: '#fafafa',
  clientEmptyBorder: '#d4d4d8',
  rowEven: '#ffffff',
  rowOdd: '#fafafa',
  rowHover: '05',
  borderLight: '#e4e4e7',
  totalBg: '08',
  totalBorder: '20',
  footerBorder: '#e4e4e7',
  inputBg: '#ffffff',
  inputPlaceholder: '#a1a1aa',
  editBorderDashed: '#d4d4d8',
  signatureBorder: '#d4d4d8',
  paymentBadgeBg: '#fafafa',
  paymentBadgeBorder: '#e4e4e7',
  paymentBadgeText: '#52525b',
  borderRadius: '0px',
}

const ligne: TemplateConfig = {
  id: 'ligne',
  name: 'Ligne',
  description: 'Séparateurs horizontaux colorés',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#111827',
  textMuted: '#6b7280',
  textFooter: '#9ca3af',
  clientBlockBg: 'transparent',
  clientBlockBorder: '#e5e7eb',
  clientEmptyBg: 'transparent',
  clientEmptyBorder: '#d1d5db',
  rowEven: '#ffffff',
  rowOdd: '#ffffff',
  rowHover: '04',
  borderLight: '#e5e7eb',
  totalBg: '06',
  totalBorder: '18',
  footerBorder: '#d1d5db',
  inputBg: '#ffffff',
  inputPlaceholder: '#9ca3af',
  editBorderDashed: '#d1d5db',
  signatureBorder: '#d1d5db',
  paymentBadgeBg: 'transparent',
  paymentBadgeBorder: '#e5e7eb',
  paymentBadgeText: '#6b7280',
  borderRadius: '6px',
  font: 'Manrope',
}

export const TEMPLATES: TemplateConfig[] = [
  classique,
  moderne,
  studio,
  elegance,
  editorial,
  audacieux,
  carbone,
  duo,
  horizon,
  lateral,
  prisme,
  pastel,
  minimaliste,
  mono,
  compact,
  ligne,
]

export function applyDarkMode(tpl: TemplateConfig): TemplateConfig {
  return {
    ...tpl,
    docBg: '#111113',
    text: '#ffffff',
    textMuted: '#a1a1aa',
    textFooter: '#71717a',
    clientBlockBg: '#1a1a1e',
    clientBlockBorder: '#2a2a30',
    clientEmptyBg: '#1a1a1e',
    clientEmptyBorder: '#2a2a30',
    rowEven: '#111113',
    rowOdd: '#161618',
    rowHover: '12',
    borderLight: '#2a2a30',
    totalBg: '15',
    totalBorder: '30',
    footerBorder: '#2a2a30',
    inputBg: '#1a1a1e',
    inputPlaceholder: '#71717a',
    editBorderDashed: '#2a2a30',
    signatureBorder: '#2a2a30',
    paymentBadgeBg: '#1a1a1e',
    paymentBadgeBorder: '#2a2a30',
    paymentBadgeText: '#a1a1aa',
  }
}

export function getTemplate(id?: string, darkMode?: boolean): TemplateConfig {
  if (!id) {
    const base = classique
    return darkMode ? applyDarkMode(base) : base
  }
  const base = TEMPLATES.find((t) => t.id === id) ?? classique
  return darkMode ? applyDarkMode(base) : base
}
