export interface TemplateConfig {
  id: string
  name: string
  description: string
  layout: 'standard' | 'banner' | 'lateral'
  docBg: string
  text: string
  textMuted: string
  textFooter: string
  clientBlockBg: string
  clientBlockBorder: string
  clientEmptyBg: string
  clientEmptyBorder: string
  rowEven: string
  rowOdd: string
  rowHover: string
  borderLight: string
  totalBg: string
  totalBorder: string
  footerBorder: string
  inputBg: string
  inputPlaceholder: string
  editBorderDashed: string
  signatureBorder: string
  paymentBadgeBg: string
  paymentBadgeBorder: string
  paymentBadgeText: string
  borderRadius: string
  font?: string
}

const classique: TemplateConfig = {
  id: 'classique',
  name: 'Classique',
  description: 'Bordures pointillées, accent bleu-gris, style comptable',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#476388',
  textMuted: '#88A0BF',
  textFooter: '#88A0BF',
  clientBlockBg: '#ffffff',
  clientBlockBorder: '#bfcee1',
  clientEmptyBg: '#E5ECF4',
  clientEmptyBorder: '#88A0BF',
  rowEven: '#ffffff',
  rowOdd: '#fafbfd',
  rowHover: '06',
  borderLight: '#bfcee1',
  totalBg: '10',
  totalBorder: '25',
  footerBorder: '#bfcee1',
  inputBg: '#ffffff',
  inputPlaceholder: '#88A0BF',
  editBorderDashed: '#bfcee1',
  signatureBorder: '#bfcee1',
  paymentBadgeBg: '#f0f3f8',
  paymentBadgeBorder: '#bfcee1',
  paymentBadgeText: '#476388',
  borderRadius: '8px',
  font: 'Nunito',
}

const moderne: TemplateConfig = {
  id: 'moderne',
  name: 'Moderne',
  description: 'Bandeau coloré, zébrage marqué, contrastes nets',
  layout: 'banner',
  docBg: '#ffffff',
  text: '#09090b',
  textMuted: '#52525b',
  textFooter: '#a1a1aa',
  clientBlockBg: '#f4f4f5',
  clientBlockBorder: '#d4d4d8',
  clientEmptyBg: '#fafafa',
  clientEmptyBorder: '#a1a1aa',
  rowEven: '#ffffff',
  rowOdd: '#f4f4f5',
  rowHover: '08',
  borderLight: '#d4d4d8',
  totalBg: '10',
  totalBorder: '30',
  footerBorder: '#18181b',
  inputBg: '#ffffff',
  inputPlaceholder: '#a1a1aa',
  editBorderDashed: '#a1a1aa',
  signatureBorder: '#a1a1aa',
  paymentBadgeBg: '#f4f4f5',
  paymentBadgeBorder: '#d4d4d8',
  paymentBadgeText: '#18181b',
  borderRadius: '10px',
}

const studio: TemplateConfig = {
  id: 'studio',
  name: 'Studio',
  description: 'Hairlines noir encre, typographie affirmée, angles vifs',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#0a0a0a',
  textMuted: '#5b5b63',
  textFooter: '#8e8e96',
  clientBlockBg: 'transparent',
  clientBlockBorder: '#0a0a0a',
  clientEmptyBg: '#ffffff',
  clientEmptyBorder: '#0a0a0a',
  rowEven: '#ffffff',
  rowOdd: '#ffffff',
  rowHover: '06',
  borderLight: '#1c1c21',
  totalBg: '0a',
  totalBorder: '55',
  footerBorder: '#0a0a0a',
  inputBg: '#ffffff',
  inputPlaceholder: '#8e8e96',
  editBorderDashed: '#b9b9c0',
  signatureBorder: '#0a0a0a',
  paymentBadgeBg: '#0a0a0a',
  paymentBadgeBorder: '#0a0a0a',
  paymentBadgeText: '#ffffff',
  borderRadius: '0px',
  font: 'Sora',
}

const elegance: TemplateConfig = {
  id: 'elegance',
  name: 'Élégance',
  description: 'Serif raffiné, papier crème, lignes pierre',
  layout: 'standard',
  docBg: '#fdfcf9',
  text: '#2d2a24',
  textMuted: '#7d776c',
  textFooter: '#a8a195',
  clientBlockBg: 'transparent',
  clientBlockBorder: '#d8d2c4',
  clientEmptyBg: '#f8f6f0',
  clientEmptyBorder: '#c9c2b2',
  rowEven: '#fdfcf9',
  rowOdd: '#f7f4ec',
  rowHover: '05',
  borderLight: '#ddd6c8',
  totalBg: '08',
  totalBorder: '20',
  footerBorder: '#c9c2b2',
  inputBg: '#fdfcf9',
  inputPlaceholder: '#a8a195',
  editBorderDashed: '#c9c2b2',
  signatureBorder: '#c9c2b2',
  paymentBadgeBg: '#f5f2e9',
  paymentBadgeBorder: '#ddd6c8',
  paymentBadgeText: '#6b6457',
  borderRadius: '2px',
  font: 'EB Garamond',
}

const editorial: TemplateConfig = {
  id: 'editorial',
  name: 'Éditorial',
  description: 'Style revue, serif littéraire, papier chamois',
  layout: 'standard',
  docBg: '#faf5ec',
  text: '#33291c',
  textMuted: '#82715c',
  textFooter: '#a59781',
  clientBlockBg: 'transparent',
  clientBlockBorder: '#d9cbb4',
  clientEmptyBg: '#f3ecdd',
  clientEmptyBorder: '#c8b894',
  rowEven: '#faf5ec',
  rowOdd: '#f3ecdd',
  rowHover: '06',
  borderLight: '#ddd0b8',
  totalBg: '0c',
  totalBorder: '28',
  footerBorder: '#33291c',
  inputBg: '#faf5ec',
  inputPlaceholder: '#a59781',
  editBorderDashed: '#c8b894',
  signatureBorder: '#c8b894',
  paymentBadgeBg: '#f3ecdd',
  paymentBadgeBorder: '#ddd0b8',
  paymentBadgeText: '#6f6049',
  borderRadius: '0px',
  font: 'Lora',
}

const audacieux: TemplateConfig = {
  id: 'audacieux',
  name: 'Audacieux',
  description: 'En-tête plein, formes très arrondies, grotesque',
  layout: 'banner',
  docBg: '#ffffff',
  text: '#0f172a',
  textMuted: '#475569',
  textFooter: '#94a3b8',
  clientBlockBg: '#e8eef6',
  clientBlockBorder: '#cbd9e8',
  clientEmptyBg: '#f1f5f9',
  clientEmptyBorder: '#b6c6d8',
  rowEven: '#ffffff',
  rowOdd: '#eef3f9',
  rowHover: '0a',
  borderLight: '#cbd9e8',
  totalBg: '1c',
  totalBorder: '45',
  footerBorder: '#cbd9e8',
  inputBg: '#ffffff',
  inputPlaceholder: '#94a3b8',
  editBorderDashed: '#b6c6d8',
  signatureBorder: '#b6c6d8',
  paymentBadgeBg: '#e8eef6',
  paymentBadgeBorder: '#cbd9e8',
  paymentBadgeText: '#33475e',
  borderRadius: '18px',
  font: 'Archivo',
}

const carbone: TemplateConfig = {
  id: 'carbone',
  name: 'Carbone',
  description: 'Papier graphite, badges inversés, géométrique',
  layout: 'banner',
  docBg: '#f2f2f3',
  text: '#131316',
  textMuted: '#4c4c53',
  textFooter: '#8a8a92',
  clientBlockBg: '#e7e7ea',
  clientBlockBorder: '#d2d2d7',
  clientEmptyBg: '#ebebee',
  clientEmptyBorder: '#bcbcc4',
  rowEven: '#f7f7f8',
  rowOdd: '#ebebee',
  rowHover: '0a',
  borderLight: '#c9c9cf',
  totalBg: '16',
  totalBorder: '38',
  footerBorder: '#131316',
  inputBg: '#f7f7f8',
  inputPlaceholder: '#8a8a92',
  editBorderDashed: '#bcbcc4',
  signatureBorder: '#bcbcc4',
  paymentBadgeBg: '#232327',
  paymentBadgeBorder: '#232327',
  paymentBadgeText: '#f2f2f3',
  borderRadius: '4px',
  font: 'Space Grotesk',
}

const duo: TemplateConfig = {
  id: 'duo',
  name: 'Duo',
  description: 'Encre marine, bandeau accent, badges sombres',
  layout: 'banner',
  docBg: '#ffffff',
  text: '#14233f',
  textMuted: '#51648a',
  textFooter: '#8c9ab8',
  clientBlockBg: '#edf1f8',
  clientBlockBorder: '#d4ddec',
  clientEmptyBg: '#f4f7fb',
  clientEmptyBorder: '#bfcce2',
  rowEven: '#ffffff',
  rowOdd: '#f2f5fa',
  rowHover: '08',
  borderLight: '#d4ddec',
  totalBg: '12',
  totalBorder: '30',
  footerBorder: '#14233f',
  inputBg: '#ffffff',
  inputPlaceholder: '#8c9ab8',
  editBorderDashed: '#bfcce2',
  signatureBorder: '#bfcce2',
  paymentBadgeBg: '#14233f',
  paymentBadgeBorder: '#14233f',
  paymentBadgeText: '#ffffff',
  borderRadius: '10px',
}

const horizon: TemplateConfig = {
  id: 'horizon',
  name: 'Horizon',
  description: 'Papier azur, bandeau épuré, géométrie aérée',
  layout: 'banner',
  docBg: '#f9fcff',
  text: '#0f3552',
  textMuted: '#5e82a0',
  textFooter: '#93afc6',
  clientBlockBg: '#edf5fc',
  clientBlockBorder: '#d3e4f2',
  clientEmptyBg: '#f2f8fd',
  clientEmptyBorder: '#bcd5ea',
  rowEven: '#f9fcff',
  rowOdd: '#eef6fc',
  rowHover: '08',
  borderLight: '#d3e4f2',
  totalBg: '12',
  totalBorder: '2e',
  footerBorder: '#d3e4f2',
  inputBg: '#f9fcff',
  inputPlaceholder: '#93afc6',
  editBorderDashed: '#bcd5ea',
  signatureBorder: '#bcd5ea',
  paymentBadgeBg: '#edf5fc',
  paymentBadgeBorder: '#d3e4f2',
  paymentBadgeText: '#3c6485',
  borderRadius: '12px',
  font: 'DM Sans',
}

const lateral: TemplateConfig = {
  id: 'lateral',
  name: 'Latéral',
  description: 'Barre latérale colorée avec infos société',
  layout: 'lateral',
  docBg: '#ffffff',
  text: '#1f2937',
  textMuted: '#64748b',
  textFooter: '#94a3b8',
  clientBlockBg: '#f5f7fa',
  clientBlockBorder: '#dde3eb',
  clientEmptyBg: '#f8fafc',
  clientEmptyBorder: '#c8d2de',
  rowEven: '#ffffff',
  rowOdd: '#f5f7fa',
  rowHover: '08',
  borderLight: '#dde3eb',
  totalBg: '10',
  totalBorder: '2a',
  footerBorder: '#dde3eb',
  inputBg: '#ffffff',
  inputPlaceholder: '#94a3b8',
  editBorderDashed: '#c8d2de',
  signatureBorder: '#c8d2de',
  paymentBadgeBg: '#f5f7fa',
  paymentBadgeBorder: '#dde3eb',
  paymentBadgeText: '#4a5a6e',
  borderRadius: '8px',
}

const prisme: TemplateConfig = {
  id: 'prisme',
  name: 'Prisme',
  description: 'Barre latérale, papier violet, intérieur arrondi',
  layout: 'lateral',
  docBg: '#fdfcff',
  text: '#2a2244',
  textMuted: '#756a99',
  textFooter: '#a39bbd',
  clientBlockBg: '#f3effb',
  clientBlockBorder: '#e0d8f0',
  clientEmptyBg: '#f7f4fc',
  clientEmptyBorder: '#cfc3e6',
  rowEven: '#fdfcff',
  rowOdd: '#f5f1fb',
  rowHover: '0a',
  borderLight: '#e0d8f0',
  totalBg: '14',
  totalBorder: '32',
  footerBorder: '#e0d8f0',
  inputBg: '#fdfcff',
  inputPlaceholder: '#a39bbd',
  editBorderDashed: '#cfc3e6',
  signatureBorder: '#cfc3e6',
  paymentBadgeBg: '#f3effb',
  paymentBadgeBorder: '#e0d8f0',
  paymentBadgeText: '#5d5181',
  borderRadius: '12px',
  font: 'Outfit',
}

const pastel: TemplateConfig = {
  id: 'pastel',
  name: 'Pastel',
  description: 'Papier rosé, très arrondi, ambiance douce',
  layout: 'standard',
  docBg: '#fdf8f9',
  text: '#53404a',
  textMuted: '#a18a95',
  textFooter: '#c0aeb7',
  clientBlockBg: '#f9eef2',
  clientBlockBorder: '#f0dce4',
  clientEmptyBg: '#fbf2f5',
  clientEmptyBorder: '#e3c8d3',
  rowEven: '#fdf8f9',
  rowOdd: '#f9eef2',
  rowHover: '08',
  borderLight: '#f0dce4',
  totalBg: '14',
  totalBorder: '30',
  footerBorder: '#f0dce4',
  inputBg: '#fdf8f9',
  inputPlaceholder: '#c0aeb7',
  editBorderDashed: '#e3c8d3',
  signatureBorder: '#e3c8d3',
  paymentBadgeBg: '#f9eef2',
  paymentBadgeBorder: '#f0dce4',
  paymentBadgeText: '#8d7280',
  borderRadius: '16px',
  font: 'Quicksand',
}

const minimaliste: TemplateConfig = {
  id: 'minimaliste',
  name: 'Minimaliste',
  description: 'Ultra-épuré, traits à peine visibles, espace généreux',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#18181b',
  textMuted: '#71717a',
  textFooter: '#a1a1aa',
  clientBlockBg: 'transparent',
  clientBlockBorder: 'transparent',
  clientEmptyBg: '#ffffff',
  clientEmptyBorder: '#d4d4d8',
  rowEven: '#ffffff',
  rowOdd: '#ffffff',
  rowHover: '04',
  borderLight: '#f0f0f2',
  totalBg: '06',
  totalBorder: '14',
  footerBorder: '#f0f0f2',
  inputBg: '#ffffff',
  inputPlaceholder: '#a1a1aa',
  editBorderDashed: '#d4d4d8',
  signatureBorder: '#d4d4d8',
  paymentBadgeBg: 'transparent',
  paymentBadgeBorder: '#e4e4e7',
  paymentBadgeText: '#71717a',
  borderRadius: '0px',
}

const mono: TemplateConfig = {
  id: 'mono',
  name: 'Mono',
  description: 'Chasse fixe, papier terminal, badges inversés',
  layout: 'standard',
  docBg: '#fbfbf8',
  text: '#20241f',
  textMuted: '#5d645c',
  textFooter: '#939a92',
  clientBlockBg: '#f1f2ec',
  clientBlockBorder: '#d8dbd0',
  clientEmptyBg: '#f5f6f1',
  clientEmptyBorder: '#c2c7b9',
  rowEven: '#fbfbf8',
  rowOdd: '#f1f2ec',
  rowHover: '08',
  borderLight: '#d8dbd0',
  totalBg: '0e',
  totalBorder: '2c',
  footerBorder: '#20241f',
  inputBg: '#fbfbf8',
  inputPlaceholder: '#939a92',
  editBorderDashed: '#c2c7b9',
  signatureBorder: '#c2c7b9',
  paymentBadgeBg: '#20241f',
  paymentBadgeBorder: '#20241f',
  paymentBadgeText: '#fbfbf8',
  borderRadius: '0px',
  font: 'JetBrains Mono',
}

const compact: TemplateConfig = {
  id: 'compact',
  name: 'Compact',
  description: 'Grille marquée, dense, sans arrondis',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#111113',
  textMuted: '#4b4b52',
  textFooter: '#8f8f97',
  clientBlockBg: '#f3f3f5',
  clientBlockBorder: '#9b9ba4',
  clientEmptyBg: '#f7f7f8',
  clientEmptyBorder: '#9b9ba4',
  rowEven: '#ffffff',
  rowOdd: '#f3f3f5',
  rowHover: '08',
  borderLight: '#9b9ba4',
  totalBg: '0e',
  totalBorder: '40',
  footerBorder: '#9b9ba4',
  inputBg: '#ffffff',
  inputPlaceholder: '#8f8f97',
  editBorderDashed: '#9b9ba4',
  signatureBorder: '#9b9ba4',
  paymentBadgeBg: '#f3f3f5',
  paymentBadgeBorder: '#9b9ba4',
  paymentBadgeText: '#34343a',
  borderRadius: '0px',
}

const ligne: TemplateConfig = {
  id: 'ligne',
  name: 'Ligne',
  description: 'Séparateurs horizontaux appuyés, gris ardoise',
  layout: 'standard',
  docBg: '#ffffff',
  text: '#1d2530',
  textMuted: '#66707d',
  textFooter: '#98a1ac',
  clientBlockBg: 'transparent',
  clientBlockBorder: '#aeb6bf',
  clientEmptyBg: '#f6f8fa',
  clientEmptyBorder: '#aeb6bf',
  rowEven: '#ffffff',
  rowOdd: '#ffffff',
  rowHover: '06',
  borderLight: '#aeb6bf',
  totalBg: '0a',
  totalBorder: '38',
  footerBorder: '#1d2530',
  inputBg: '#ffffff',
  inputPlaceholder: '#98a1ac',
  editBorderDashed: '#aeb6bf',
  signatureBorder: '#aeb6bf',
  paymentBadgeBg: 'transparent',
  paymentBadgeBorder: '#aeb6bf',
  paymentBadgeText: '#4e5866',
  borderRadius: '6px',
  font: 'Manrope',
}

export const TEMPLATES: TemplateConfig[] = [
  classique,
  moderne,
  studio,
  elegance,
  editorial,
  audacieux,
  carbone,
  duo,
  horizon,
  lateral,
  prisme,
  pastel,
  minimaliste,
  mono,
  compact,
  ligne,
]

export function applyDarkMode(tpl: TemplateConfig): TemplateConfig {
  return {
    ...tpl,
    docBg: '#111113',
    text: '#ffffff',
    textMuted: '#a1a1aa',
    textFooter: '#71717a',
    clientBlockBg: '#1a1a1e',
    clientBlockBorder: '#2a2a30',
    clientEmptyBg: '#1a1a1e',
    clientEmptyBorder: '#2a2a30',
    rowEven: '#111113',
    rowOdd: '#161618',
    rowHover: '12',
    borderLight: '#2a2a30',
    totalBg: '15',
    totalBorder: '30',
    footerBorder: '#2a2a30',
    inputBg: '#1a1a1e',
    inputPlaceholder: '#71717a',
    editBorderDashed: '#2a2a30',
    signatureBorder: '#2a2a30',
    paymentBadgeBg: '#1a1a1e',
    paymentBadgeBorder: '#2a2a30',
    paymentBadgeText: '#a1a1aa',
  }
}

export function getTemplate(id?: string, darkMode?: boolean): TemplateConfig {
  if (!id) {
    const base = classique
    return darkMode ? applyDarkMode(base) : base
  }
  const base = TEMPLATES.find((t) => t.id === id) ?? classique
  return darkMode ? applyDarkMode(base) : base
}
